### ISSUE TITLE
Use 2-space indenting

### ISSUE THREAD

**Issue by rom1504** [Egoscio/gelato#2]
To avoid that kind of unreadable super-indentation https://github.com/Egoscio/gelato/blob/master/lib/proxy.js#L71

**Comment by Egoscio-zz** [comment]
https://github.com/Egoscio/gelato/commit/d8156223e09eac51145a1641fe99bc5684a1b721 fixed the problem as well as anything else related to syntax inconsistency, etc...

**Comment by rom1504** [comment]
@Egoscio as you're following standard style, you might want to do http://standardjs.com/#what-you-might-do-if-youre-clever so things are checked automatically ;) (might even add a [circle.yml](https://github.com/PrismarineJS/prismarine-nbt/blob/master/circle.yml) so checks get done when you push)
